import {
  TabletSmartphone,
  Flag,
  Book,
  ChartPie,
  Code,
  Database,
  Lightbulb,
  Smartphone,
  ShoppingCart,
  User,
  Settings,
  Check,
  Pencil,
  Clipboard,
  Globe,
  Network,
  MapPin,
} from "lucide-react";

export const availableIcons = [
  { name: "TabletSmartphone", icon: TabletSmartphone },
  { name: "Flag", icon: Flag },
  { name: "Book", icon: Book },
  { name: "ChartPie", icon: ChartPie },
  { name: "Code", icon: Code },
  { name: "Database", icon: Database },
  { name: "Lightbulb", icon: Lightbulb },
  { name: "Smartphone", icon: Smartphone },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "User", icon: User },
  { name: "Settings", icon: Settings },
  { name: "Check", icon: Check },
  { name: "Pencil", icon: Pencil },
  { name: "Clipboard", icon: Clipboard },
  { name: "Globe", icon: Globe },
  { name: "Network", icon: Network },
  { name: "MapPin", icon: MapPin },
];
